name: Azure Service Creation automation

on:
  workflow_dispatch: 

env:
  AZURE_RESOURCE_GROUP: ImpetusRG               # set this to your Azure Resource group's name  
  AZURE_LOCATION: eastus                         # set this to your azure resource group location   
  AZURE_SQL_SERVERNAME: SqldbImpetus         # set SQL Server  
  AZURE_SQL_DATABASE: HackathonSqlDB    # set sqladmin user
  AZURE_SQLFIREWALL_IP: 0.0.0.0    # set this to all Azure IPs
  AZURE_APP_PLAN: webappimpetusplan
  AZURE_APIAPP_NAME: apiappimpetus
  
  
jobs:
  azuresetup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.DEPLOYGITHUB }}

# Provision a Azure sQL Database on Azure
    - name: Azure Service creation
      uses: azure/CLI@v1
      with:
        azcliversion: latest
        inlineScript: |
          az sql server create --name ${{ env.AZURE_SQL_SERVERNAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --location ${{ env.AZURE_LOCATION }} --admin-user ${{ secrets.SQLADMINUSER }}  --admin-password ${{ secrets.SQLADMINPASS }}
          az sql server firewall-rule create --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --server ${{ env.AZURE_SQL_SERVERNAME }} -n AllowYourIp --start-ip-address ${{ env.AZURE_SQLFIREWALL_IP }} --end-ip-address ${{ env.AZURE_SQLFIREWALL_IP }}
          az sql db create -g ${{ env.AZURE_RESOURCE_GROUP }} -s ${{ env.AZURE_SQL_SERVERNAME }} -n ${{ env.AZURE_SQL_DATABASE }} --service-objective S0
          az appservice plan create --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --name ${{ env.AZURE_APP_PLAN }} --is-linux --sku S1
          az webapp create --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --plan ${{ env.AZURE_APP_PLAN }} --name ${{ env.AZURE_APIAPP_NAME }}  --runtime "DOTNETCORE|3.1"

    # Azure logout 
    - name: logout
      run: |
        az logout 
 
   
